# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TicTacToe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for TicTacToe
  pod 'RIBs', :path => '../../../'
  pod 'SnapKit', '~> 4.0.0'
  pod 'RxCocoa', '~> 6.5'

end